//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ws_clientedniruc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.consultabata.com/", ConfigurationName="ws_clientedniruc.Cons_ClienteSoap")]
    public interface Cons_ClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_validatdabgwb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ws_validatdabgwb(string _cod_tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_validatdabgwb", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ws_validatdabgwbAsync(string _cod_tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_update_cliente(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_update_clienteAsync(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_venta_empl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_update_venta_empl(string _Tip_Id_Ven, string _Nro_Dni_Ven, string _Cod_Tda_Ven, string _Nro_Doc_Ven, string _Tip_Doc_Ven, string _Ser_Doc_Ven, string _Num_Doc_Ven, string _Fec_Doc_Ven, string _Est_Doc_Ven, string _Fc_Nin_Ven);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_venta_empl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_update_venta_emplAsync(string _Tip_Id_Ven, string _Nro_Dni_Ven, string _Cod_Tda_Ven, string _Nro_Doc_Ven, string _Tip_Doc_Ven, string _Ser_Doc_Ven, string _Num_Doc_Ven, string _Fec_Doc_Ven, string _Est_Doc_Ven, string _Fc_Nin_Ven);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_vales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_update_vales(string _serie, string _correlativo, string _cod_tda_venta, string _dni_venta, string _nombres_venta, string _fecha_doc, string _tipo_doc, string _serie_doc, string _numero_doc, string _estado_doc, string _fc_nint, string _email_venta, string _telefono_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_vales", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_update_valesAsync(string _serie, string _correlativo, string _cod_tda_venta, string _dni_venta, string _nombres_venta, string _fecha_doc, string _tipo_doc, string _serie_doc, string _numero_doc, string _estado_doc, string _fc_nint, string _email_venta, string _telefono_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_barra_dni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.Barra[] ws_buscar_barra_dni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_barra_dni", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Barra[]> ws_buscar_barra_dniAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/generacupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.GeneraCuponBata generacupon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/generacupon", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.GeneraCuponBata> generacuponAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_getbarra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.GeneraCuponBata ws_getbarra(CapaPresentacion.ws_clientedniruc.GeneraCuponBata genera_cupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_getbarra", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.GeneraCuponBata> ws_getbarraAsync(CapaPresentacion.ws_clientedniruc.GeneraCuponBata genera_cupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_getprombata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.PromBata ws_getprombata(string cod, string tda, string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_getprombata", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.PromBata> ws_getprombataAsync(string cod, string tda, string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_vales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ws_buscar_vales(string _correlativo, string _code, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_vales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ws_buscar_valesAsync(string _correlativo, string _code, string _tda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_desxdni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ws_buscar_desxdni(string _dni, string _codtda, string _tip_des);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_buscar_desxdni", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ws_buscar_desxdniAsync(string _dni, string _codtda, string _tip_des);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_conscliente(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_consclienteAsync(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente_bata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_conscliente_bata(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_conscliente_bata", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_conscliente_bataAsync(string _dniruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_insertcliente_bata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ws_insertcliente_bata(string dniruc, string nombres, string apelpat, string apemat, string email, string telefono, string codtda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_insertcliente_bata", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ws_insertcliente_bataAsync(string dniruc, string nombres, string apelpat, string apemat, string email, string telefono, string codtda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_reniec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_persona_reniec(string _dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_reniec", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_reniecAsync(string _dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_info_sunat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.Data_Sunat ws_info_sunat(string _ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_info_sunat", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Data_Sunat> ws_info_sunatAsync(string _ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_sunat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_persona_sunat(string _ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_persona_sunat", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_sunatAsync(string _ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_ActivaGiftCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ws_ActivaGiftCard(string numero, string dni_activa, string nombres, string apepat, string apemat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_ActivaGiftCard", ReplyAction="*")]
        System.Threading.Tasks.Task ws_ActivaGiftCardAsync(string numero, string dni_activa, string nombres, string apepat, string apemat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_GrabarSQL_Ticket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ws_GrabarSQL_Ticket(string tienda, string serie, string codigo, string fecha, string dni, string nombres, string apepat, string apemat, string forpag, string tarjeta, string nro_tarj, string detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_GrabarSQL_Ticket", ReplyAction="*")]
        System.Threading.Tasks.Task ws_GrabarSQL_TicketAsync(string tienda, string serie, string codigo, string fecha, string dni, string nombres, string apepat, string apemat, string forpag, string tarjeta, string nro_tarj, string detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_BuscarGiftCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_BuscarGiftCard(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_BuscarGiftCard", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_BuscarGiftCardAsync(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_BuscarTicketGF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_BuscarTicketGF(string empresa, string serie, string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_BuscarTicketGF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_BuscarTicketGFAsync(string empresa, string serie, string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_verifica_version_apltda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ws_verifica_version_apltda(string _cod_tda, string _nom_apl, string _ver_apl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_verifica_version_apltda", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ws_verifica_version_apltdaAsync(string _cod_tda, string _nom_apl, string _ver_apl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_apltda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_update_apltda(string _cod_tda, string _nom_apl, string _ver_apl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_update_apltda", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_update_apltdaAsync(string _cod_tda, string _nom_apl, string _ver_apl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_lista_soporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaPresentacion.ws_clientedniruc.Soporte[] ws_lista_soporte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.consultabata.com/ws_lista_soporte", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Soporte[]> ws_lista_soporteAsync();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.consultabata.com/")]
    public partial class Barra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barraField;
        
        private string promocionField;
        
        private System.DateTime fechacField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string barra {
            get {
                return this.barraField;
            }
            set {
                this.barraField = value;
                this.RaisePropertyChanged("barra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string promocion {
            get {
                return this.promocionField;
            }
            set {
                this.promocionField = value;
                this.RaisePropertyChanged("promocion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechac {
            get {
                return this.fechacField;
            }
            set {
                this.fechacField = value;
                this.RaisePropertyChanged("fechac");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.consultabata.com/")]
    public partial class Soporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string celularField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.consultabata.com/")]
    public partial class Data_Sunat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private string direccionField;
        
        private string nombresField;
        
        private string rucField;
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.consultabata.com/")]
    public partial class PromBata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool validaField;
        
        private string nom_promField;
        
        private System.DateTime fecha_iniField;
        
        private System.DateTime fecha_finField;
        
        private decimal por_desField;
        
        private decimal max_parField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool valida {
            get {
                return this.validaField;
            }
            set {
                this.validaField = value;
                this.RaisePropertyChanged("valida");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nom_prom {
            get {
                return this.nom_promField;
            }
            set {
                this.nom_promField = value;
                this.RaisePropertyChanged("nom_prom");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fecha_ini {
            get {
                return this.fecha_iniField;
            }
            set {
                this.fecha_iniField = value;
                this.RaisePropertyChanged("fecha_ini");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                this.fecha_finField = value;
                this.RaisePropertyChanged("fecha_fin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal por_des {
            get {
                return this.por_desField;
            }
            set {
                this.por_desField = value;
                this.RaisePropertyChanged("por_des");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal max_par {
            get {
                return this.max_parField;
            }
            set {
                this.max_parField = value;
                this.RaisePropertyChanged("max_par");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.consultabata.com/")]
    public partial class GeneraCuponBata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombres_prinField;
        
        private string nombresField;
        
        private string apepatField;
        
        private string apematField;
        
        private string emailField;
        
        private string dniField;
        
        private decimal pordesField;
        
        private System.DateTime fechainiField;
        
        private System.DateTime fechafinField;
        
        private decimal paresmaxField;
        
        private string grupoField;
        
        private string barraField;
        
        private string correlativoField;
        
        private string serieField;
        
        private string tipcupField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombres_prin {
            get {
                return this.nombres_prinField;
            }
            set {
                this.nombres_prinField = value;
                this.RaisePropertyChanged("nombres_prin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apepat {
            get {
                return this.apepatField;
            }
            set {
                this.apepatField = value;
                this.RaisePropertyChanged("apepat");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string apemat {
            get {
                return this.apematField;
            }
            set {
                this.apematField = value;
                this.RaisePropertyChanged("apemat");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal pordes {
            get {
                return this.pordesField;
            }
            set {
                this.pordesField = value;
                this.RaisePropertyChanged("pordes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime fechaini {
            get {
                return this.fechainiField;
            }
            set {
                this.fechainiField = value;
                this.RaisePropertyChanged("fechaini");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime fechafin {
            get {
                return this.fechafinField;
            }
            set {
                this.fechafinField = value;
                this.RaisePropertyChanged("fechafin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal paresmax {
            get {
                return this.paresmaxField;
            }
            set {
                this.paresmaxField = value;
                this.RaisePropertyChanged("paresmax");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string barra {
            get {
                return this.barraField;
            }
            set {
                this.barraField = value;
                this.RaisePropertyChanged("barra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string correlativo {
            get {
                return this.correlativoField;
            }
            set {
                this.correlativoField = value;
                this.RaisePropertyChanged("correlativo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string tipcup {
            get {
                return this.tipcupField;
            }
            set {
                this.tipcupField = value;
                this.RaisePropertyChanged("tipcup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Cons_ClienteSoapChannel : CapaPresentacion.ws_clientedniruc.Cons_ClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Cons_ClienteSoapClient : System.ServiceModel.ClientBase<CapaPresentacion.ws_clientedniruc.Cons_ClienteSoap>, CapaPresentacion.ws_clientedniruc.Cons_ClienteSoap {
        
        public Cons_ClienteSoapClient() {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cons_ClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cons_ClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ws_validatdabgwb(string _cod_tda) {
            return base.Channel.ws_validatdabgwb(_cod_tda);
        }
        
        public System.Threading.Tasks.Task<bool> ws_validatdabgwbAsync(string _cod_tda) {
            return base.Channel.ws_validatdabgwbAsync(_cod_tda);
        }
        
        public string ws_update_cliente(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda) {
            return base.Channel.ws_update_cliente(_ruc, _nombres, _apepat, _apemat, _telefono, _email, _tda);
        }
        
        public System.Threading.Tasks.Task<string> ws_update_clienteAsync(string _ruc, string _nombres, string _apepat, string _apemat, string _telefono, string _email, string _tda) {
            return base.Channel.ws_update_clienteAsync(_ruc, _nombres, _apepat, _apemat, _telefono, _email, _tda);
        }
        
        public string ws_update_venta_empl(string _Tip_Id_Ven, string _Nro_Dni_Ven, string _Cod_Tda_Ven, string _Nro_Doc_Ven, string _Tip_Doc_Ven, string _Ser_Doc_Ven, string _Num_Doc_Ven, string _Fec_Doc_Ven, string _Est_Doc_Ven, string _Fc_Nin_Ven) {
            return base.Channel.ws_update_venta_empl(_Tip_Id_Ven, _Nro_Dni_Ven, _Cod_Tda_Ven, _Nro_Doc_Ven, _Tip_Doc_Ven, _Ser_Doc_Ven, _Num_Doc_Ven, _Fec_Doc_Ven, _Est_Doc_Ven, _Fc_Nin_Ven);
        }
        
        public System.Threading.Tasks.Task<string> ws_update_venta_emplAsync(string _Tip_Id_Ven, string _Nro_Dni_Ven, string _Cod_Tda_Ven, string _Nro_Doc_Ven, string _Tip_Doc_Ven, string _Ser_Doc_Ven, string _Num_Doc_Ven, string _Fec_Doc_Ven, string _Est_Doc_Ven, string _Fc_Nin_Ven) {
            return base.Channel.ws_update_venta_emplAsync(_Tip_Id_Ven, _Nro_Dni_Ven, _Cod_Tda_Ven, _Nro_Doc_Ven, _Tip_Doc_Ven, _Ser_Doc_Ven, _Num_Doc_Ven, _Fec_Doc_Ven, _Est_Doc_Ven, _Fc_Nin_Ven);
        }
        
        public string ws_update_vales(string _serie, string _correlativo, string _cod_tda_venta, string _dni_venta, string _nombres_venta, string _fecha_doc, string _tipo_doc, string _serie_doc, string _numero_doc, string _estado_doc, string _fc_nint, string _email_venta, string _telefono_venta) {
            return base.Channel.ws_update_vales(_serie, _correlativo, _cod_tda_venta, _dni_venta, _nombres_venta, _fecha_doc, _tipo_doc, _serie_doc, _numero_doc, _estado_doc, _fc_nint, _email_venta, _telefono_venta);
        }
        
        public System.Threading.Tasks.Task<string> ws_update_valesAsync(string _serie, string _correlativo, string _cod_tda_venta, string _dni_venta, string _nombres_venta, string _fecha_doc, string _tipo_doc, string _serie_doc, string _numero_doc, string _estado_doc, string _fc_nint, string _email_venta, string _telefono_venta) {
            return base.Channel.ws_update_valesAsync(_serie, _correlativo, _cod_tda_venta, _dni_venta, _nombres_venta, _fecha_doc, _tipo_doc, _serie_doc, _numero_doc, _estado_doc, _fc_nint, _email_venta, _telefono_venta);
        }
        
        public CapaPresentacion.ws_clientedniruc.Barra[] ws_buscar_barra_dni(string dni) {
            return base.Channel.ws_buscar_barra_dni(dni);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Barra[]> ws_buscar_barra_dniAsync(string dni) {
            return base.Channel.ws_buscar_barra_dniAsync(dni);
        }
        
        public CapaPresentacion.ws_clientedniruc.GeneraCuponBata generacupon() {
            return base.Channel.generacupon();
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.GeneraCuponBata> generacuponAsync() {
            return base.Channel.generacuponAsync();
        }
        
        public CapaPresentacion.ws_clientedniruc.GeneraCuponBata ws_getbarra(CapaPresentacion.ws_clientedniruc.GeneraCuponBata genera_cupon) {
            return base.Channel.ws_getbarra(genera_cupon);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.GeneraCuponBata> ws_getbarraAsync(CapaPresentacion.ws_clientedniruc.GeneraCuponBata genera_cupon) {
            return base.Channel.ws_getbarraAsync(genera_cupon);
        }
        
        public CapaPresentacion.ws_clientedniruc.PromBata ws_getprombata(string cod, string tda, string dni) {
            return base.Channel.ws_getprombata(cod, tda, dni);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.PromBata> ws_getprombataAsync(string cod, string tda, string dni) {
            return base.Channel.ws_getprombataAsync(cod, tda, dni);
        }
        
        public System.Data.DataSet ws_buscar_vales(string _correlativo, string _code, string _tda) {
            return base.Channel.ws_buscar_vales(_correlativo, _code, _tda);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ws_buscar_valesAsync(string _correlativo, string _code, string _tda) {
            return base.Channel.ws_buscar_valesAsync(_correlativo, _code, _tda);
        }
        
        public System.Data.DataSet ws_buscar_desxdni(string _dni, string _codtda, string _tip_des) {
            return base.Channel.ws_buscar_desxdni(_dni, _codtda, _tip_des);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ws_buscar_desxdniAsync(string _dni, string _codtda, string _tip_des) {
            return base.Channel.ws_buscar_desxdniAsync(_dni, _codtda, _tip_des);
        }
        
        public System.Data.DataTable ws_conscliente(string _dniruc) {
            return base.Channel.ws_conscliente(_dniruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_consclienteAsync(string _dniruc) {
            return base.Channel.ws_consclienteAsync(_dniruc);
        }
        
        public System.Data.DataTable ws_conscliente_bata(string _dniruc) {
            return base.Channel.ws_conscliente_bata(_dniruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_conscliente_bataAsync(string _dniruc) {
            return base.Channel.ws_conscliente_bataAsync(_dniruc);
        }
        
        public bool ws_insertcliente_bata(string dniruc, string nombres, string apelpat, string apemat, string email, string telefono, string codtda) {
            return base.Channel.ws_insertcliente_bata(dniruc, nombres, apelpat, apemat, email, telefono, codtda);
        }
        
        public System.Threading.Tasks.Task<bool> ws_insertcliente_bataAsync(string dniruc, string nombres, string apelpat, string apemat, string email, string telefono, string codtda) {
            return base.Channel.ws_insertcliente_bataAsync(dniruc, nombres, apelpat, apemat, email, telefono, codtda);
        }
        
        public System.Data.DataTable ws_persona_reniec(string _dni) {
            return base.Channel.ws_persona_reniec(_dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_reniecAsync(string _dni) {
            return base.Channel.ws_persona_reniecAsync(_dni);
        }
        
        public CapaPresentacion.ws_clientedniruc.Data_Sunat ws_info_sunat(string _ruc) {
            return base.Channel.ws_info_sunat(_ruc);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Data_Sunat> ws_info_sunatAsync(string _ruc) {
            return base.Channel.ws_info_sunatAsync(_ruc);
        }
        
        public System.Data.DataTable ws_persona_sunat(string _ruc) {
            return base.Channel.ws_persona_sunat(_ruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_persona_sunatAsync(string _ruc) {
            return base.Channel.ws_persona_sunatAsync(_ruc);
        }
        
        public void ws_ActivaGiftCard(string numero, string dni_activa, string nombres, string apepat, string apemat) {
            base.Channel.ws_ActivaGiftCard(numero, dni_activa, nombres, apepat, apemat);
        }
        
        public System.Threading.Tasks.Task ws_ActivaGiftCardAsync(string numero, string dni_activa, string nombres, string apepat, string apemat) {
            return base.Channel.ws_ActivaGiftCardAsync(numero, dni_activa, nombres, apepat, apemat);
        }
        
        public void ws_GrabarSQL_Ticket(string tienda, string serie, string codigo, string fecha, string dni, string nombres, string apepat, string apemat, string forpag, string tarjeta, string nro_tarj, string detail) {
            base.Channel.ws_GrabarSQL_Ticket(tienda, serie, codigo, fecha, dni, nombres, apepat, apemat, forpag, tarjeta, nro_tarj, detail);
        }
        
        public System.Threading.Tasks.Task ws_GrabarSQL_TicketAsync(string tienda, string serie, string codigo, string fecha, string dni, string nombres, string apepat, string apemat, string forpag, string tarjeta, string nro_tarj, string detail) {
            return base.Channel.ws_GrabarSQL_TicketAsync(tienda, serie, codigo, fecha, dni, nombres, apepat, apemat, forpag, tarjeta, nro_tarj, detail);
        }
        
        public System.Data.DataTable ws_BuscarGiftCard(string numero) {
            return base.Channel.ws_BuscarGiftCard(numero);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_BuscarGiftCardAsync(string numero) {
            return base.Channel.ws_BuscarGiftCardAsync(numero);
        }
        
        public System.Data.DataTable ws_BuscarTicketGF(string empresa, string serie, string numero) {
            return base.Channel.ws_BuscarTicketGF(empresa, serie, numero);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_BuscarTicketGFAsync(string empresa, string serie, string numero) {
            return base.Channel.ws_BuscarTicketGFAsync(empresa, serie, numero);
        }
        
        public bool ws_verifica_version_apltda(string _cod_tda, string _nom_apl, string _ver_apl) {
            return base.Channel.ws_verifica_version_apltda(_cod_tda, _nom_apl, _ver_apl);
        }
        
        public System.Threading.Tasks.Task<bool> ws_verifica_version_apltdaAsync(string _cod_tda, string _nom_apl, string _ver_apl) {
            return base.Channel.ws_verifica_version_apltdaAsync(_cod_tda, _nom_apl, _ver_apl);
        }
        
        public string ws_update_apltda(string _cod_tda, string _nom_apl, string _ver_apl) {
            return base.Channel.ws_update_apltda(_cod_tda, _nom_apl, _ver_apl);
        }
        
        public System.Threading.Tasks.Task<string> ws_update_apltdaAsync(string _cod_tda, string _nom_apl, string _ver_apl) {
            return base.Channel.ws_update_apltdaAsync(_cod_tda, _nom_apl, _ver_apl);
        }
        
        public CapaPresentacion.ws_clientedniruc.Soporte[] ws_lista_soporte() {
            return base.Channel.ws_lista_soporte();
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ws_clientedniruc.Soporte[]> ws_lista_soporteAsync() {
            return base.Channel.ws_lista_soporteAsync();
        }
    }
}
